export const ADD_TO_SALES_BILL = "ADD_TO_SALES_BILL";
export const REMOVE_FROM_SALES_BILL = "REMOVE_FROM_SALES_BILL";
export const ADJUST_QUANTITY = "ADJUST_QUANTITY";
export const ADJUST_DISCOUNT_AMOUNT = "ADJUST_DISCOUNT_AMOUNT";
export const ADJUST_DISCOUNT_PERCENTAGE = "ADJUST_DISCOUNT_PERCENTAGE";
export const ADJUST_UNIT = "ADJUST_UNIT";
